### ISSUE TITLE
Is it possible to generate Diagrams from FSM code?

### ISSUE THREAD

**Issue by bennycode** [eram/typescript-fsm#13]
Hello @eram, I really like the API design of your "typescript-fsm" library. It looks simple, yet powerful. I was wondering if it would be possible to generate the diagram of your "Basic Example" from the code?

**Comment by eram** [comment]
@bennycode something like teaching chatGPT to generate a state-changing mermaid diagram?

**Comment by eram** [comment]
for example, i ask chat:

pls create a mermaid state diagram for the following state machine: 

```
// these are the states and events for the door
enum States { closing = 0, closed, opening, opened, broken };
enum Events { open = 100, openComplete, close, closeComplete, break };

// lets define the transitions that will govern the state-machine
const transitions = [
  /* fromState        event                 toState         callback */
  t(States.closed,    Events.opened,        States.opening, onOpen),
  t(States.opening,   Events.openComplete,  States.opened,  justLog),
  t(States.opened,    Events.close,         States.closing, onClose),
  t(States.closing,   Events.closeComplete, States.closed,  justLog),
  t(States.closed,    Events.break,         States.broken,  justLog),
  t(States.opened,    Events.break,         States.broken,  justLog),
  t(States.opening,   Events.break,         States.broken,  justLog),
  t(States.closing,   Events.break,         States.broken,  justLog),
];
```

and i get an correct answer:

```
stateDiagram
    [*] --> closed
    closed --> opening : open
    opening --> opened : openComplete
    opened --> closing : close
    closing --> closed : closeComplete
    closed --> broken : break
    opened --> broken : break
    opening --> broken : break
    closing --> broken : break
```

**Comment by bennycode** [comment]
That's cool! Preferably I would like to get Markdown code (using Mermaid syntax) directly from your library. With using TypeScript for code analysis this should be possible and would be a kick-ass feature for this lib! :D

```mermaid
stateDiagram
    [*] --> closed
    closed --> opening : open
    opening --> opened : openComplete
    opened --> closing : close
    closing --> closed : closeComplete
    closed --> broken : break
    opened --> broken : break
    opening --> broken : break
    closing --> broken : break
```

**Comment by eram** [comment]
more than happy for you to send a PR with a `toMermaid()` function that outputs the Mermaid state diagram as a string.

**Comment by khill-fbmc** [comment]
What do we think of something like this?

```typescript
// Function to generate the Mermaid.js diagram code
export function generateMermaidDiagram(
  transitions: ITransition<States, Events, () => void>[],
  title?: string
) {
  let diagram = "stateDiagram-v2\n";

  if (title) {
    diagram = `---\ntitle: ${title}\n---\n${diagram}`;
  }

  diagram += `  [*] --> ${transitions[0].fromState}\n`;

  // Loop over transitions and generate the appropriate Mermaid code
  transitions.forEach(transition => {
    const fromState = States[transition.fromState];
    const toState = States[transition.toState];
    const event = Events[transition.event];

    diagram += `  ${fromState} --> ${toState}: ${event}\n`;
  });

  diagram += `  ${transitions[transitions.length - 1].toState} --> [*]\n`;

  return diagram;
}
```

![image](https://github.com/user-attachments/assets/0fa3d0a1-4870-43db-a439-98006e6308e3)

**Comment by khill-fbmc** [comment]
It's also important to label your `enum`s with strings instead of numbers like the example shows

![image](https://github.com/user-attachments/assets/e201f442-9ab1-45f6-b7b7-75d5e8b2f212)

**Comment by eram** [comment]
cool >> send a PR.
- make diagram an array and join it with "\n" in the end: `diagram.join("\n");`
- in typescript you don't need those strings added to the enum. it's built-in the language (look at the generated JS code)

**Comment by khill-fbmc** [comment]
But when I had the enum as `number`s then when an error throws for an invalid transition, it shows an un-helpful message
![image](https://github.com/user-attachments/assets/28e6afc1-353b-4b35-a3df-b8a9154807e4)

When I switched to using strings, then I got an error message that helped me find the problem.
![image](https://github.com/user-attachments/assets/3e0c2d12-850d-4b81-afb0-93d068db4b23)

**Comment by eram** [comment]
Of course, I don't mind you adding strings to enums in your code just inside this repo.

**Comment by khill-fbmc** [comment]
Do you mean, you would like:
1. The README to stay with integer enums?
2. Just have my the test door class use the strings so the `toMermaid` tests work?
