### ISSUE TITLE
Generate Mermaid State Diagrams

### ISSUE THREAD

**Issue by khill-fbmc** [eram/typescript-fsm#22]
To aid in the generation of state charts, we should update the example to use string enums instead of integers.

With the code I suggested in #13, if you do not use strings for the enums, then the mermaid code it would generate is not useful :(
![image](https://github.com/user-attachments/assets/d1bd9fff-f678-4398-90b0-e1c75b7a5715)

**Comment by khill-fbmc** [comment]
Is a new npm release coming so I can remove the dependency on my fork?

**Comment by eram** [comment]
v1.5.1 was published

**Comment by khill-fbmc** [comment]
> v1.5.1 was published

For some reason the badge isn't showing correctly in the readme
![image](https://github.com/user-attachments/assets/4e3ab1ee-787d-427a-8e72-04baf3ddf97d)
